### ISSUE TITLE
SymmetricProgressBar animates before startAnimation() called

### ISSUE THREAD

**Issue by mDadashi** [ayltai/Android-Lib-SymmetricProgressBar#1]
Hi
I am using this library in my project and first of all i have to admit that it works perfect (thanks)
when I add it to XML layout, It automatically starts to animate even before I call start animation.
Of course when I call stop animation, it stops, but it isn't the proper functionality

I add it to the layout like this:

<Controls.SymmetricProgressBar
        android:id="@+id/progress_bar_bottom"
        android:layout_width="match_parent"
        android:layout_alignParentBottom="true"
android:layout_height="6dp" />

and catch in my fragment like this:
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
mRootView = (ViewGroup) inflater.inflate(R.layout.fragment_book_list, container, false);
mProgressBar = (SymmetricProgressBar) mRootView.findViewById(R.id.progress_bar_bottom);
}

am I missing something?

**Comment by ayltai** [comment]
Yes by default if you use XML to create the widget it animates automatically upon `onAttachedToWindow()`. If you programmatically add it to a parent view it will also animate upon `onAttachedToWindow()`.

This is because it makes no sense to add it to a view but does not animate. If for whatever reason you really need to disable auto-start, you can amend the source `SymmetricProgressBar.java` and change `onAttachedToWindow()` method.

**Comment by mDadashi** [comment]
Actually, It does make sense to add it and not to start animation. that is why you have implemented startAnimation() and stopAnimation() methods. one simple scenario is that I have a task which starts by a click, I want to have the progressbar in my XML and start it when task starts and stop it when task ends. I should show and hide the view instead of starting and stopping the animation.
on the other hand isAnimating() always returns true or I have to call stopAnimation() right after catching ProgreesBar in my code. so what is the use if always true?

As I said I appreciate your efforts and I am using it in my project but I would recommend the behavior of ProgressBar should be kind of close to logical.
