### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by hatamiarash7** [ayltai/Android-Lib-SymmetricProgressBar#2]
hi, thank you for this good idea
there is some problems in your code : 

**1-** `animator.setRepeatMode(Animator.RESTART);` should be `animator.setRepeatMode(ValueAnimator.RESTART);`

**2-** in `integers.xml` you can't use **integer-array** ... use normal array instead because we can't add color value there and also you colors is normal number !!! put color codes there : 
`<array name="SymmetricProgressBar_colors">  
        <item>#FF0000</item>  
        <item>#FFFF00</item>  
        <item>#00FF00</item>  
        <item>#00FFFF</item>  
    </array>`

**3-** you can write like this : `(Float) this.animators.get(i).getAnimatedValue()` instead of `((Float)this.animators.get(i).getAnimatedValue()).floatValue()`

**Comment by ayltai** [comment]
Hi, thanks for letting me know. Can you open a pull request so we can fix it?

For no.3, I intentionally write it this way, to remind that type casting happens here.
